package com.bignerdranch.android.tortuganews.api

import com.bignerdranch.android.tortuganews.models.NewsResponse
import com.bignerdranch.android.tortuganews.util.Constants.Companion.API_KEY
import retrofit2.Response
import retrofit2.http.GET
import retrofit2.http.Query

interface NewsAPI {

    //defines single API requests we can execute from code
    //1st - get all breaking news
    //we want to get data from our api --> GET request
    @GET("v2/top-headlines")
    //function that gets the breaking news
    suspend fun getBreakingNews(
        @Query("country")
        countryCode: String = "us",
        @Query("page")
        pageNumber: Int = 1,
        @Query("apiKey")
        apiKey: String = API_KEY
    ):Response<NewsResponse>  //coroutines //NewsResponse - use it because it is a response object generated by Retrofit

    @GET("v2/everything")
    //function that gets all news
    suspend fun searchForNews(
        @Query("q")
        searchQuery: String,
        @Query("page")
        pageNumber: Int = 1,
        @Query("apiKey")
        apiKey: String = API_KEY
    ):Response<NewsResponse>
}